baseurl = "https://www.nickklauer.info"
languageCode = "en-us"
title = "Nick Klauer"
[params]
    description = ""
    googleAnalytics = "UA-27148269-1"

[[params.social]]
    title = "coding"
    icon = "github"
    url = "https://github.com/klauern"
[[params.social]]
    title = "musing"
    icon = "twitter"
    url = "https://twitter.com/klauern"
[[params.social]]
    title = "rambling"
    icon = "rss-square"
    url = "https://blog.nickklauer.info"
[[params.social]]
    title = "glad-handing"
    icon = "linkedin"
    url = "https://linkedin.com/in/nickklauer"
[[params.social]]
    title = "lecturing"
    icon = "envelope-o"
    url = "mailto:klauer@gmail.com"
[[params.social]]
    title = "credentialing"
    icon = "file-text"
    url = "https://docs.google.com/document/d/1EY-DBSnOZzoKiLArBvkevnfWCGHOKFzKytm1BL0NhJs/pub?embedded=true"
