baseurl = "http://bio.nickklauer.info"
languageCode = "en-us"
title = "Nick Klauer"
[params]
    description = "Coding, Parenting, Husbanding, Living, Soldiering On"
    googleAnalytics = "UA-27148269-1"

[[params.social]]
    title = "coding"
    icon = "github"
    url = "https://github.com/klauern"
[[params.social]]
    title = "musing"
    icon = "twitter"
    url = "https://twitter.com/klauern"
[[params.social]]
    title = "rambling"
    icon = "wordpress"
    url = "http://blog.nickklauer.info"
[[params.social]]
    title = "glad-handing"
    icon = "linkedin"
    url = "https://linkedin.com/nick.klauer"
[[params.social]]
    title = "lecturing"
    icon = "envelope-o"
    url = "mailto:klauer@gmail.com"
